spring.application.name=springboot-playground
spring.datasource.url=jdbc:postgresql://localhost:5432/springdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret-key=fd67d93b9248732cc869e7c1a24e99d498fe68757649ecf46e0798fa8119523b
security.jwt.expiration-time=3600000